### ISSUE TITLE
endpoint beforeSave callback

### ISSUE THREAD

**Issue by Nic0tiN** [UseMuffin/Github#7]
There is an error in "webservice\src\Model\Endpoint.php" at line 841.

The line is 
`$event = $this->dispatchEvent('Model.beforeSave', compact('entity', 'options'));`

and shold be
`$event = $this->dispatchEvent('Model.beforeSave', compact('resource', 'options'));`

**Comment by ADmad** [comment]
This plugin doesn't even have a `src\Model\Endpoint.php`  did you mean to post this on [Webservices](https://github.com/UseMuffin/Webservice) repo?

**Comment by Nic0tiN** [comment]
Yes, it was meant to Webservices. I'll post on the correct repo.
